In [45]:
import pandas as pd

In [46]:
df= pd.read_csv("../data/NewsRealCOVID-19.csv")
# df1= pd.read_csv("../data/NewsRealCOVID-19.csv")

In [47]:
df.head(10)

,Unnamed: 0,type,fact_check_url,news_url,title,newstitle,content,abstract,publish_date,meta_keywords
0,0,article,healthline.com,https://www.healthline.com/health-news/coronav...,Coronavirus Outbreak: Live Updates,"""Coronavirus Outbreak: Daily Updates""",experts warn most states that are reopening st...,the new coronavirus disease outbreak first ide...,NaN,"""coronavirus outbreak, viral outbreak, viral i..."
1,1,article,healthline.com,https://www.healthline.com/health-news/screen-...,"Screen Time Doesn’t Hurt Kids’ Social Skills, ...","""Screen Time Doesn't Hurt Kids' Social Skills,...",a new study finds an increase in screen time d...,new research found that school age children in...,NaN,"""screen time, child development, smartphones, ..."
2,2,article,healthline.com,https://www.healthline.com/health-news/heres-e...,Here’s Exactly Where We Are with Vaccines and ...,"""Where We're at with Vaccines and Treatments f...",scientists around the world are working on a n...,scientists around the world are working on a n...,NaN,"""covid-19 coronavirus outbreak research progre..."
3,3,article,healthline.com,https://www.healthline.com/health-news/heres-w...,Here’s What Happens to the Body After Contract...,"""Here's What Happens to the Body After Contrac...",coronaviruses cause respiratory illnesses so t...,heres what we know so far about how covid-19 a...,NaN,"""coronavirus, viral infection, viral outbreak,..."
4,4,article,healthline.com,https://www.healthline.com/health-news/why-you...,Why You Should Be Skeptical of Early Results o...,"""Why You Should Be Skeptical of Leaked Results...",medical experts are studying if remdesivir can...,with no approved treatment specific for covid-...,NaN,"""covid-19, covornavirus, novel coronavirus, vi..."
5,5,article,healthline.com,https://www.healthline.com/health-news/what-yo...,What Your Social Media Posts Say About Your St...,"""What Your Social Media Posts Say About Your S...",your social media posts may say more about you...,here 's how our social media posts reveal how ...,NaN,"""COVID 19, coronavirus, depression, anxiety, s..."
6,6,article,healthline.com,https://www.healthline.com/health-news/rural-a...,Rural America Could Be the Region Hardest Hit ...,"""Rural America Could Be Hardest Hit by COVID-19""",experts say rural areas have older populations...,experts say rural areas have older populations...,NaN,"""COVID19 coronavirus outbreak rural areas Midw..."
7,7,article,healthline.com,https://www.healthline.com/health-news/dont-us...,Experts Warning: Don’t Use Off-Label Medicatio...,"""Experts Warn: Don't Use Off-Label Medications...",an early study indicated an antimalarial drug ...,a tweet by president trump heightened interest...,NaN,"""drug medication treatments for coronavirus co..."
8,8,article,healthline.com,https://www.healthline.com/health-news/effects...,Why Soaking Up the Sun to Treat COVID-19 Isn’t...,"""Why Soaking Up the Sun to Treat COVID-19 Isn’...",experts say that while some studies have shown...,experts say that while some studies have shown...,NaN,"""COVID 19, sunlight, coronavirus, UV rays"""
9,9,article,healthline.com,https://www.healthline.com/health-news/what-to...,What to Know About a Long Recovery Period Afte...,"""What to Know About a Long Recovery Period Aft...",for people who were hospitalized with covid-19...,even for people who have officially recovered ...,NaN,"""covid-19, coronavirus, viral infection, viral..."

In [48]:
df.columns

Index(['Unnamed: 0', 'type', 'fact_check_url', 'news_url', 'title',
       'newstitle', 'content', 'abstract', 'publish_date', 'meta_keywords'],
      dtype='object')

In [49]:
df1 = df[["title", "content"]]

In [50]:
df1.head(10)

,title,content
0,Coronavirus Outbreak: Live Updates,experts warn most states that are reopening st...
1,"Screen Time Doesn’t Hurt Kids’ Social Skills, ...",a new study finds an increase in screen time d...
2,Here’s Exactly Where We Are with Vaccines and ...,scientists around the world are working on a n...
3,Here’s What Happens to the Body After Contract...,coronaviruses cause respiratory illnesses so t...
4,Why You Should Be Skeptical of Early Results o...,medical experts are studying if remdesivir can...
5,What Your Social Media Posts Say About Your St...,your social media posts may say more about you...
6,Rural America Could Be the Region Hardest Hit ...,experts say rural areas have older populations...
7,Experts Warning: Don’t Use Off-Label Medicatio...,an early study indicated an antimalarial drug ...
8,Why Soaking Up the Sun to Treat COVID-19 Isn’t...,experts say that while some studies have shown...
9,What to Know About a Long Recovery Period Afte...,for people who were hospitalized with covid-19...

In [54]:
df1["label"] = 1
df1.head(10)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\81674874.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["label"] = 1

,title,content,label
0,Coronavirus Outbreak: Live Updates,experts warn most states that are reopening st...,1
1,"Screen Time Doesn’t Hurt Kids’ Social Skills, ...",a new study finds an increase in screen time d...,1
2,Here’s Exactly Where We Are with Vaccines and ...,scientists around the world are working on a n...,1
3,Here’s What Happens to the Body After Contract...,coronaviruses cause respiratory illnesses so t...,1
4,Why You Should Be Skeptical of Early Results o...,medical experts are studying if remdesivir can...,1
5,What Your Social Media Posts Say About Your St...,your social media posts may say more about you...,1
6,Rural America Could Be the Region Hardest Hit ...,experts say rural areas have older populations...,1
7,Experts Warning: Don’t Use Off-Label Medicatio...,an early study indicated an antimalarial drug ...,1
8,Why Soaking Up the Sun to Treat COVID-19 Isn’t...,experts say that while some studies have shown...,1
9,What to Know About a Long Recovery Period Afte...,for people who were hospitalized with covid-19...,1

In [55]:
df1.isnull().sum()

title        0
content    193
label        0
dtype: int64

In [56]:
df2 = df1[(df1["title"].str.strip() != "") | (df1["content"].str.strip() != "")]

In [57]:
df2.head(10)

,title,content,label
0,Coronavirus Outbreak: Live Updates,experts warn most states that are reopening st...,1
1,"Screen Time Doesn’t Hurt Kids’ Social Skills, ...",a new study finds an increase in screen time d...,1
2,Here’s Exactly Where We Are with Vaccines and ...,scientists around the world are working on a n...,1
3,Here’s What Happens to the Body After Contract...,coronaviruses cause respiratory illnesses so t...,1
4,Why You Should Be Skeptical of Early Results o...,medical experts are studying if remdesivir can...,1
5,What Your Social Media Posts Say About Your St...,your social media posts may say more about you...,1
6,Rural America Could Be the Region Hardest Hit ...,experts say rural areas have older populations...,1
7,Experts Warning: Don’t Use Off-Label Medicatio...,an early study indicated an antimalarial drug ...,1
8,Why Soaking Up the Sun to Treat COVID-19 Isn’t...,experts say that while some studies have shown...,1
9,What to Know About a Long Recovery Period Afte...,for people who were hospitalized with covid-19...,1

In [59]:
from ftfy import fix_text

df2["title"] = df2["title"].astype(str).apply(fix_text)
df2["content"] = df2["content"].astype(str).apply(fix_text)

In [61]:
import re

pattern = r"(http\S+|www\S+|\.com|\.org|\.net)"

df3 = df2[
    ~df2["title"].str.contains(pattern, case=False, na=False) &
    ~df2["content"].str.contains(pattern, case=False, na=False)
]

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\3362736457.py:6: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ~df2["title"].str.contains(pattern, case=False, na=False) &
C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\3362736457.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ~df2["content"].str.contains(pattern, case=False, na=False)

In [62]:
import re

pattern = r"(http\S+|www\S+|\.com|\.org|\.net)"

df3[df3["title"].str.contains(pattern, case=False, na=False)]

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\4042515335.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df3[df3["title"].str.contains(pattern, case=False, na=False)]

Empty DataFrame
Columns: [title, content, label]
Index: []

In [65]:
print(df3.duplicated().sum())

26

In [71]:
df3["title"] = df3["title"].str.lower().str.strip()
df4 = df3.drop_duplicates(subset=["title"])

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\732087254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["title"] = df3["title"].str.lower().str.strip()

In [72]:
df4["content"] = df4["content"].str.lower().str.strip()
df5 = df4.drop_duplicates(subset=["content"])

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\2135527479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4["content"] = df4["content"].str.lower().str.strip()

In [73]:
print(df5.duplicated().sum())

0

In [77]:
import re

def clean_text(text):
    if pd.isna(text):
        return text
    
    text = text.lower()
    
    # Fix common errors
    text = text.replace("covid-lg", "covid-19")
    
    # Remove "getty images"
    text = re.sub(r'getty images', '', text)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df5['content'] = df5['content'].apply(clean_text)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\579166561.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['content'] = df5['content'].apply(clean_text)

In [79]:
final_df = df5[df5['content'].str.len() > 50]

In [82]:
import re

def remove_prefix(text):
    if pd.isna(text):
        return text
    
    text = re.sub(r'^.*?coronavirus news\.?', '', text)
    return text.strip()

final_df['content'] = final_df['content'].apply(remove_prefix)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\3443062440.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['content'] = final_df['content'].apply(remove_prefix)

In [84]:
import re

def clean_title(text):
    if pd.isna(text):
        return text
    
    text = text.lower()
    
    # Fix common spacing issues
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)  # camel case
    text = re.sub(r'(?<=\w)(?=where|finds|you|the)', ' ', text)
    
    # Fix common typos
    text = text.replace("doesnt", "doesn't")
    text = text.replace("dont", "don't")
    text = text.replace("arent", "aren't")
    text = text.replace("dotft", "don't")
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

final_df['title'] = final_df['title'].apply(clean_title)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\2874523486.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['title'] = final_df['title'].apply(clean_title)

In [86]:
import re
def shorten_text(text):
    if pd.isna(text):
        return text
    sentences = re.split(r'(?<=[.!?]) +', text)
    short = ' '.join(sentences[:3])
    return ' '.join(short.split()[:60])  # max 60 words
final_df['content'] = final_df['content'].apply(shorten_text)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_11096\4189755440.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['content'] = final_df['content'].apply(shorten_text)

In [ ]:
# df4=df3.drop("content",axis=1)

In [87]:
final_df.to_csv("../data/Covidreal.csv", index=False)

In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("../data/Covidfake.csv")

In [8]:
df.head(20)

                                                title  label
0   A "face mask exempt card" shared on social med...      0
1   A test on video with a gas detector shows that...      0
2   A painting depicting children in face masks wa...      0
3   According to Bill Gates the COVID-19 RNA vacci...      0
4   Meme shows Florida Surgeon General saying: Eve...      0
5   Alexandria Ocasio-Cortez tweeted "It's vital t...      0
6   COVID-19 cases are "up only because of our big...      0
7   If you are licensed to carry a concealed weapo...      0
8   Claim that Rep. Alexandria Ocasio-Cortez tweet...      0
9   In North Carolina "you can be charged with a c...      0
10  A "face mask exempt card" allows you to cite t...      0
11  A scientific study shows that cannabis is more...      0
12  A short portion of an interview given by discr...      0
13  Social media posts shared thousands of times i...      0
14  "Joe Biden and the Democrats want to prosecute...      0
15  The U.S. Occupational Safety and Health Admini...      0
16  Gov. Gavin Newsom "has no legal authority" to ...      0
17  President Trump's claim that he inherited no v...      0
18  "OSHA says masks don't work" to reduce COVID-1...      0
19  Bill Gates who has led harmful vaccination cam...      0

In [27]:
df1=df.rename(columns={"title":"text"})

In [28]:
df1.head(10)

                                                text  label
0  A "face mask exempt card" shared on social med...      0
1  A test on video with a gas detector shows that...      0
2  A painting depicting children in face masks wa...      0
3  According to Bill Gates the COVID-19 RNA vacci...      0
4  Meme shows Florida Surgeon General saying: Eve...      0
5  Alexandria Ocasio-Cortez tweeted "It's vital t...      0
6  COVID-19 cases are "up only because of our big...      0
7  If you are licensed to carry a concealed weapo...      0
8  Claim that Rep. Alexandria Ocasio-Cortez tweet...      0
9  In North Carolina "you can be charged with a c...      0

In [29]:
import pandas as pd

def split_statement(text):
    words = text.split()
    
    # First 12 words → title
    title = ' '.join(words[:12])
    
    # Full text → text
    return pd.Series([title, text])

# Apply OUTSIDE the function
df1[['title', 'statement']] = df1['text'].apply(split_statement)

In [30]:
df1.head(10)

,text,label,title,statement
0,"A ""face mask exempt card"" shared on social med...",0,"A ""face mask exempt card"" shared on social med...","A ""face mask exempt card"" shared on social med..."
1,A test on video with a gas detector shows that...,0,A test on video with a gas detector shows that...,A test on video with a gas detector shows that...
2,A painting depicting children in face masks wa...,0,A painting depicting children in face masks wa...,A painting depicting children in face masks wa...
3,According to Bill Gates the COVID-19 RNA vacci...,0,According to Bill Gates the COVID-19 RNA vacci...,According to Bill Gates the COVID-19 RNA vacci...
4,Meme shows Florida Surgeon General saying: Eve...,0,Meme shows Florida Surgeon General saying: Eve...,Meme shows Florida Surgeon General saying: Eve...
5,"Alexandria Ocasio-Cortez tweeted ""It's vital t...",0,"Alexandria Ocasio-Cortez tweeted ""It's vital t...","Alexandria Ocasio-Cortez tweeted ""It's vital t..."
6,"COVID-19 cases are ""up only because of our big...",0,"COVID-19 cases are ""up only because of our big...","COVID-19 cases are ""up only because of our big..."
7,If you are licensed to carry a concealed weapo...,0,If you are licensed to carry a concealed weapo...,If you are licensed to carry a concealed weapo...
8,Claim that Rep. Alexandria Ocasio-Cortez tweet...,0,Claim that Rep. Alexandria Ocasio-Cortez tweet...,Claim that Rep. Alexandria Ocasio-Cortez tweet...
9,"In North Carolina ""you can be charged with a c...",0,"In North Carolina ""you can be charged with a c...","In North Carolina ""you can be charged with a c..."

In [32]:
df2=df1.drop("text",axis=1)
df2.head(10)

,label,title,statement
0,0,"A ""face mask exempt card"" shared on social med...","A ""face mask exempt card"" shared on social med..."
1,0,A test on video with a gas detector shows that...,A test on video with a gas detector shows that...
2,0,A painting depicting children in face masks wa...,A painting depicting children in face masks wa...
3,0,According to Bill Gates the COVID-19 RNA vacci...,According to Bill Gates the COVID-19 RNA vacci...
4,0,Meme shows Florida Surgeon General saying: Eve...,Meme shows Florida Surgeon General saying: Eve...
5,0,"Alexandria Ocasio-Cortez tweeted ""It's vital t...","Alexandria Ocasio-Cortez tweeted ""It's vital t..."
6,0,"COVID-19 cases are ""up only because of our big...","COVID-19 cases are ""up only because of our big..."
7,0,If you are licensed to carry a concealed weapo...,If you are licensed to carry a concealed weapo...
8,0,Claim that Rep. Alexandria Ocasio-Cortez tweet...,Claim that Rep. Alexandria Ocasio-Cortez tweet...
9,0,"In North Carolina ""you can be charged with a c...","In North Carolina ""you can be charged with a c..."

In [33]:
df3=df2.rename(columns={"statement":"text"})
df3.head(10)

,label,title,text
0,0,"A ""face mask exempt card"" shared on social med...","A ""face mask exempt card"" shared on social med..."
1,0,A test on video with a gas detector shows that...,A test on video with a gas detector shows that...
2,0,A painting depicting children in face masks wa...,A painting depicting children in face masks wa...
3,0,According to Bill Gates the COVID-19 RNA vacci...,According to Bill Gates the COVID-19 RNA vacci...
4,0,Meme shows Florida Surgeon General saying: Eve...,Meme shows Florida Surgeon General saying: Eve...
5,0,"Alexandria Ocasio-Cortez tweeted ""It's vital t...","Alexandria Ocasio-Cortez tweeted ""It's vital t..."
6,0,"COVID-19 cases are ""up only because of our big...","COVID-19 cases are ""up only because of our big..."
7,0,If you are licensed to carry a concealed weapo...,If you are licensed to carry a concealed weapo...
8,0,Claim that Rep. Alexandria Ocasio-Cortez tweet...,Claim that Rep. Alexandria Ocasio-Cortez tweet...
9,0,"In North Carolina ""you can be charged with a c...","In North Carolina ""you can be charged with a c..."

In [34]:
df4 = df3[['title', 'text', 'label']]

df4.head(10)

,title,text,label
0,"A ""face mask exempt card"" shared on social med...","A ""face mask exempt card"" shared on social med...",0
1,A test on video with a gas detector shows that...,A test on video with a gas detector shows that...,0
2,A painting depicting children in face masks wa...,A painting depicting children in face masks wa...,0
3,According to Bill Gates the COVID-19 RNA vacci...,According to Bill Gates the COVID-19 RNA vacci...,0
4,Meme shows Florida Surgeon General saying: Eve...,Meme shows Florida Surgeon General saying: Eve...,0
5,"Alexandria Ocasio-Cortez tweeted ""It's vital t...","Alexandria Ocasio-Cortez tweeted ""It's vital t...",0
6,"COVID-19 cases are ""up only because of our big...","COVID-19 cases are ""up only because of our big...",0
7,If you are licensed to carry a concealed weapo...,If you are licensed to carry a concealed weapo...,0
8,Claim that Rep. Alexandria Ocasio-Cortez tweet...,Claim that Rep. Alexandria Ocasio-Cortez tweet...,0
9,"In North Carolina ""you can be charged with a c...","In North Carolina ""you can be charged with a c...",0

In [35]:
df4.to_csv("../data/finaldatasets/covidfake.csv",index=False)

In [36]:
df6=pd.read_csv("../data/covidreal.csv")

In [37]:
df6.head(10)

,title,content,label
0,coronavirus outbreak: live updates,experts warn most states that are reopening st...,1
1,"screen time doesn't hurt kids' social skills, ...",a new study finds an increase in screen time d...,1
2,here's exactly where we are with vaccines and ...,scientists around the world are working on a n...,1
3,here's what happens to the body after contract...,coronaviruses cause respiratory illnesses so t...,1
4,why you should be skeptical of early results o...,medical experts are studying if remdesivir can...,1
5,what your social media posts say about your st...,your social media posts may say more about you...,1
6,rural america could be the region hardest hit ...,experts say rural areas have older populations...,1
7,experts warning: don't use off-label medicatio...,an early study indicated an antimalarial drug ...,1
8,why soaking up the sun to treat covid-19 isn't...,experts say that while some studies have shown...,1
9,what to know about a long recovery period afte...,for people who were hospitalized with covid-19...,1

In [39]:
df7=df6.rename(columns={"content":"text"})
df7.head(10)

,title,text,label
0,coronavirus outbreak: live updates,experts warn most states that are reopening st...,1
1,"screen time doesn't hurt kids' social skills, ...",a new study finds an increase in screen time d...,1
2,here's exactly where we are with vaccines and ...,scientists around the world are working on a n...,1
3,here's what happens to the body after contract...,coronaviruses cause respiratory illnesses so t...,1
4,why you should be skeptical of early results o...,medical experts are studying if remdesivir can...,1
5,what your social media posts say about your st...,your social media posts may say more about you...,1
6,rural america could be the region hardest hit ...,experts say rural areas have older populations...,1
7,experts warning: don't use off-label medicatio...,an early study indicated an antimalarial drug ...,1
8,why soaking up the sun to treat covid-19 isn't...,experts say that while some studies have shown...,1
9,what to know about a long recovery period afte...,for people who were hospitalized with covid-19...,1

In [41]:
df7.to_csv("../data/finaldatasets/covidreal1.csv",index=False)