In [1]:
import pandas as pd

In [ ]:
df=pd.read_csv("../data/finaldatasets/combinedfully_liar123.csv")
df1=pd.read_csv("../data/finaldatasets/covidfake.csv")
df2=pd.read_csv("../data/finaldatasets/covidreal1.csv")
df3=pd.read_csv("../data/finaldatasets/NewDatasetliarx1.csv")
df4=pd.read_csv("../data/finaldatasets/previousfinal22.csv")
df6=pd.read_csv("../data/finaldatasets/misleadingfile.csv")

In [3]:
merge_df = pd.concat([df, df1, df2, df3, df4, df6], ignore_index=True)

In [4]:
final_df = merge_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [5]:
final_df.head(20)

,title,text,label
0,mueller just told trump to f*ck off with his t...,on wednesday donald trump warned the special c...,0
1,a day when fashion and tragedy continue to int...,sunday morning officially the fourth day of ne...,0
2,Only four countries in the world allow abortio...,Only four countries in the world allow abortio...,1
3,"hungary pm orban, u.s. financier soros clash a...",budapest reuters hungarian prime minister vikt...,1
4,one of the worst right-wing trolls just got ba...,right wing super troll and breitbart com contr...,0
5,senators close to bipartisan deal on health ex...,washington reuters two u s senators from both ...,1
6,embattled alabama republican senate candidate ...,washington reuters embattled republican u s se...,1
7,poland's refusal to accept muslim migrants may...,warsaw reuters the european commission s decis...,0
8,California cut about $1.3 billion in child car...,California cut about $1.3 billion in child car...,2
9,Florida's legal challenge of the federal healt...,Florida's legal challenge of the federal healt...,1
10,Federal spending on entitlements is projected ...,Federal spending on entitlements is projected ...,2
11,u.s. republicans push back on democratic gun-c...,washington reuters u s congressional republica...,1
12,john oliver issues formal invitation to trump'...,finding out donald trump was his own publicist...,0
13,Says that when President Bill Clinton raised t...,Says that when President Bill Clinton raised t...,0
14,conservative leader sends stern message to mit...,matt schlapp the leader of the american conser...,0
15,"new orleans ""club"" advertises ""meet and greet""...",wow it looks like dem candidate for governor j...,1
16,uk's may says brexit talks must focus on futur...,london reuters british prime minister theresa ...,0
17,new zealand pm says ban on foreign home buyers...,wellington reuters new zealand prime minister ...,0
18,"city, county leaders ask court to lift injunct...",washington leaders from more than 70 cities an...,0
19,watch: colin kaepernick's worst nightmare,you might remember this bright moment from whe...,0

In [6]:
final_df.info

<bound method DataFrame.info of                                                    title  \
0      mueller just told trump to f*ck off with his t...
1      a day when fashion and tragedy continue to int...
2      Only four countries in the world allow abortio...
3      hungary pm orban, u.s. financier soros clash a...
4      one of the worst right-wing trolls just got ba...
...                                                  ...
71223  abbas asks pope, world powers, to intervene ag...
71224  Ohio Republicans made significant gains during...
71225  chicago schools budget counts on uncertain fun...
71226  The Governor did not consult members of his ow...
71227  "We have an unemployment (rate of) 1.5 in Boon...

                                                    text  label
0      on wednesday donald trump warned the special c...      0
1      sunday morning officially the fourth day of ne...      0
2      Only four countries in the world allow abortio...      1
3      budapest reuters hungarian prime minister vikt...      1
4      right wing super troll and breitbart com contr...      0
...                                                  ...    ...
71223  ramallah west bank reuters palestinian preside...      1
71224  Ohio Republicans made significant gains during...      2
71225  chicago reuters a fiscal 2018 budget unveiled ...      1
71226  The Governor did not consult members of his ow...      0
71227  "We have an unemployment (rate of) 1.5 in Boon...      1

[71228 rows x 3 columns]>

In [7]:
counts = final_df['label'].value_counts()

print("False (0):", counts.get(0, 0))
print("True (1):", counts.get(1, 0))
print("Misleading (2):", counts.get(2, 0))

False (0): 30569
True (1): 33614
Misleading (2): 7045

In [8]:
print((final_df['label'].value_counts(normalize=True) * 100).round(2))

label
1    47.19
0    42.92
2     9.89
Name: proportion, dtype: float64

In [ ]:
import re

def normalize_text(text: str):
    # Fix quotes
    text = text.replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'")

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+", "", text)

    # Keep important punctuation (! ? .)
    text = re.sub(r"[^a-zA-Z0-9\s\.\!\?]", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


def shorten_text(text: str, max_words=60):
    words = text.split()
    return " ".join(words[:max_words])


# def create_input(title: str, text: str):
#     title = "" if title is None else title
#     text = "" if text is None else text

#     title = normalize_text(title)
#     text = normalize_text(text)

#     if text.strip() == "":
#         return title

#     short_text = shorten_text(text)
#     return title + " " + short_text


# def preprocess_pipeline(title: str, text: str):
#     input_text = create_input(title, text)

#     return {
#         "input_text": input_text
#     }
# Apply normalization
final_df['title'] = final_df['title'].fillna('').apply(normalize_text)
final_df['text'] = final_df['text'].fillna('').apply(normalize_text)

# Shorten text
final_df['text'] = final_df['text'].apply(shorten_text)


# Reset index
final_df = final_df.reset_index(drop=True)

# Check
final_df.head(30)
# final_df.to_csv("../data/finaldatasets/completedata.csv",index=False)
# # =========================
# # TEST
# # =========================
# title = "BREAKING!!! Pakistan wins the T20 World Cup 2026!!!"
# text = "Pakistan has officially won the T20 World Cup after defeating India in a thrilling final match."

# print(preprocess_pipeline(title, text))

,title,text,label
0,mueller just told trump to fck off with his th...,on wednesday donald trump warned the special c...,0
1,a day when fashion and tragedy continue to int...,sunday morning officially the fourth day of ne...,0
2,only four countries in the world allow abortio...,only four countries in the world allow abortio...,1
3,hungary pm orban u.s. financier soros clash as...,budapest reuters hungarian prime minister vikt...,1
4,one of the worst rightwing trolls just got ban...,right wing super troll and breitbart com contr...,0
5,senators close to bipartisan deal on health ex...,washington reuters two u s senators from both ...,1
6,embattled alabama republican senate candidate ...,washington reuters embattled republican u s se...,1
7,polands refusal to accept muslim migrants may ...,warsaw reuters the european commission s decis...,0
8,california cut about 1.3 billion in child care...,california cut about 1.3 billion in child care...,2
9,floridas legal challenge of the federal health...,floridas legal challenge of the federal health...,1
10,federal spending on entitlements is projected ...,federal spending on entitlements is projected ...,2
11,u.s. republicans push back on democratic gunco...,washington reuters u s congressional republica...,1
12,john oliver issues formal invitation to trumps...,finding out donald trump was his own publicist...,0
13,says that when president bill clinton raised t...,says that when president bill clinton raised t...,0
14,conservative leader sends stern message to mit...,matt schlapp the leader of the american conser...,0
15,new orleans club advertises meet and greet for...,wow it looks like dem candidate for governor j...,1
16,uks may says brexit talks must focus on future...,london reuters british prime minister theresa ...,0
17,new zealand pm says ban on foreign home buyers...,wellington reuters new zealand prime minister ...,0
18,city county leaders ask court to lift injuncti...,washington leaders from more than 70 cities an...,0
19,watch colin kaepernicks worst nightmare,you might remember this bright moment from whe...,0
20,racist president jackson to be replaced with b...,obama has filled his cabinet with radical yes ...,0
21,meet the trump truthers media figures insist b...,the summer of trump officially closes with its...,0
22,as u.s. weighs afghan strategy hopes set on fl...,kabul reuters this version of the july 23 stor...,1
23,judge proposes may 7 trial date for former tru...,washington reuters a federal judge on friday p...,1
24,trump advisers to discuss whether u.s. stays i...,washington reuters white house advisers and tr...,1
25,presidents bush and clinton be humble in victo...,dallas reuters former u s presidents george w ...,1
26,says he supported the 1994 crime bill because ...,says he supported the 1994 crime bill because ...,0
27,despite republicans best efforts scotus just a...,much to the dismay of so called pro life repub...,0
28,says central texas river water sent to downstr...,says central texas river water sent to downstr...,2
29,because as a senator toomey stood up for wall ...,because as a senator toomey stood up for wall ...,2

In [10]:
final_df.info

<bound method DataFrame.info of                                                    title  \
0      mueller just told trump to fck off with his th...
1      a day when fashion and tragedy continue to int...
2      only four countries in the world allow abortio...
3      hungary pm orban u.s. financier soros clash as...
4      one of the worst rightwing trolls just got ban...
...                                                  ...
71223  abbas asks pope world powers to intervene agai...
71224  ohio republicans made significant gains during...
71225  chicago schools budget counts on uncertain fun...
71226  the governor did not consult members of his ow...
71227  we have an unemployment rate of 1.5 in boone c...

                                                    text  label
0      on wednesday donald trump warned the special c...      0
1      sunday morning officially the fourth day of ne...      0
2      only four countries in the world allow abortio...      1
3      budapest reuters hungarian prime minister vikt...      1
4      right wing super troll and breitbart com contr...      0
...                                                  ...    ...
71223  ramallah west bank reuters palestinian preside...      1
71224  ohio republicans made significant gains during...      2
71225  chicago reuters a fiscal 2018 budget unveiled ...      1
71226  the governor did not consult members of his ow...      0
71227  we have an unemployment rate of 1.5 in boone c...      1

[71228 rows x 3 columns]>

In [11]:
final_df.to_csv("../data/finaldatasets/completedataset.csv",index=False)

In [2]:
import pandas as pd
df=pd.read_csv("../data/finaldatasets/completedataset.csv")
df1=pd.read_csv("../data/finaldatasets/misleadingfile.csv")

In [3]:
m_df = pd.concat([df, df1], ignore_index=True)

In [4]:
final_df = m_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [5]:
final_df.head(10)

,title,text,label
0,you are fake news! trump presides over turbule...,new york reuters the drama started early at do...,1
1,suicide bomber attacks nato convoy in afghanis...,kabul reuters a suicide bomber in an explosive...,0
2,bill letting people bring concealed guns acros...,washington reuters people would be able to bri...,1
3,check out new ben jerrys flavor touting americ...,in 2016 ben jerry s co founder ben cohen s net...,0
4,says sen. sherrod brown admitted that his 787 ...,says sen. sherrod brown admitted that his 787 ...,0
5,watch crooked hillary make claim no lives lost...,what about chris stevens sean smith glen doher...,0
6,police union warns trump sanctuary city cuts c...,washington reuters leaders of the largest poli...,1
7,says apple ceo steve jobs told president obama...,says apple ceo steve jobs told president obama...,2
8,photo showing putin holding nose in car with t...,photo showing putin holding nose in car with t...,2
9,naacp wants georgia confederate monument remov...,the atlanta naacp is totally over the top on t...,0

In [8]:
counts = final_df['label'].value_counts()

print("False (0):", counts.get(0, 0))
print("True (1):", counts.get(1, 0))
print("Misleading (2):", counts.get(2, 0))

False (0): 30569
True (1): 33614
Misleading (2): 10553

In [9]:
mis = final_df[final_df['label'] == 2]

mis_extra = mis.sample(n=8000, replace=True, random_state=42)

ff2 = pd.concat([final_df, mis_extra])

In [10]:
ff3 = ff2.sample(frac=1).reset_index(drop=True)

In [12]:
counts = ff3['label'].value_counts()

print("False (0):", counts.get(0, 0))
print("True (1):", counts.get(1, 0))
print("Misleading (2):", counts.get(2, 0))

False (0): 30569
True (1): 33614
Misleading (2): 18553

In [13]:
ff3.to_csv("../data/trainingdatasetfinal_18k_misleading.csv",index=False, encoding="utf-8-sig")

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("../data/Now1_Fullfinal.csv")

In [7]:
df['label'].value_counts()

label
1    32221
0    31329
Name: count, dtype: int64