In [1]:
import pandas as pd

In [19]:
traindf=pd.read_csv("../data/trainliar.csv")
testdf=pd.read_csv("../data/testliar.csv")
validdf=pd.read_csv("../data/validliar.csv")

In [20]:
combined_df = pd.concat([traindf, testdf, validdf], ignore_index=True)

# Save to new CSV
combined_df.to_csv("../data/combined_liar.csv", index=False)

print("Files merged successfully!")
print(combined_df.shape)

Files merged successfully!
(12836, 14)

In [21]:
df1=pd.read_csv("../data/combined_liar.csv")

In [22]:
df1.columns

Index(['id', 'label', 'statement', 'subject', 'speaker', 'job_title',
       'state_info', 'party_affiliation', 'barely_true_counts', 'false_counts',
       'half_true_counts', 'mostly_true_counts', 'pants_on_fire_counts',
       'context'],
      dtype='object')

In [23]:
# Keep only required columns
filtered_df = combined_df[['statement', 'context', 'label']]

# # Optional: reset index
# filtered_df = filtered_df.reset_index(drop=True)

# # Save new dataset
# filtered_df.to_csv("../data/final_liar_dataset.csv", index=False)

# print(filtered_df.head())
# print(filtered_df.shape)

In [24]:
filtered_df.head(10)

,statement,context,label
0,Says the Annies List political group supports ...,a mailer,0
1,When did the decline of coal start? It started...,a floor speech.,1
2,"Hillary Clinton agrees with John McCain ""by vo...",Denver,2
3,Health care reform legislation is likely to ma...,a news release,0
4,The economic turnaround started at the end of ...,an interview on CNN,1
5,The Chicago Bears have had more starting quart...,a an online opinion-piece,3
6,Jim Dunnam has not lived in the district he re...,a press release.,4
7,"""I'm the only person on this stage who has wor...","a Democratic debate in Philadelphia, Pa.",1
8,"However, it took $19.5 million in Oregon Lotte...",a website,1
9,Says GOP primary opponents Glenn Grothman and ...,an online video,2

In [25]:
filtered_df = filtered_df.rename(columns={
    'statement': 'title',
    'context': 'text'
})

In [26]:
filtered_df.head(40)

,title,text,label
0,Says the Annies List political group supports ...,a mailer,0
1,When did the decline of coal start? It started...,a floor speech.,1
2,"Hillary Clinton agrees with John McCain ""by vo...",Denver,2
3,Health care reform legislation is likely to ma...,a news release,0
4,The economic turnaround started at the end of ...,an interview on CNN,1
5,The Chicago Bears have had more starting quart...,a an online opinion-piece,3
6,Jim Dunnam has not lived in the district he re...,a press release.,4
7,"""I'm the only person on this stage who has wor...","a Democratic debate in Philadelphia, Pa.",1
8,"However, it took $19.5 million in Oregon Lotte...",a website,1
9,Says GOP primary opponents Glenn Grothman and ...,an online video,2
10,"For the first time in history, the share of th...",a speech,2
11,"Since 2000, nearly 12 million Americans have s...",a tweet,1
12,When Mitt Romney was governor of Massachusetts...,an interview with CBN News,0
13,The economy bled $24 billion due to the govern...,a Doonesbury strip in the Sunday comics,2
14,Most of the (Affordable Care Act) has already ...,"comments on ""Fox News Sunday""",4
15,"In this last election in November, ... 63 perc...","a town hall in Austin, Texas",1
16,"""McCain opposed a requirement that the governm...",a radio ad,3
17,"U.S. Rep. Ron Kind, D-Wis., and his fellow Dem...",a news release,4
18,"Water rates in Manila, Philippines, were raise...",a congressional hearing,1
19,"Almost 100,000 people left Puerto Rico last year.",an interview with Bloomberg News,2
20,Women and men both are making less when you ad...,a campaign debate,0
21,The United States has the highest corporate ta...,"a discussion on Fox News' ""The Five""",2
22,We just had the best year for the auto industr...,remarks at a Kentucky rally,2
23,"Says Scott Walker favors cutting up to 350,000...",a campaign TV ad,1
24,Says Mitt Romney wants to get rid of Planned P...,a radio ad,4
25,I dont know who (Jonathan Gruber) is.,a news conference,0
26,Hate crimes against American Muslims and mosqu...,a speech after a terrorist attack in Orlando,2
27,Rick Perry has never lost an election and rema...,an oped column.,1
28,ISIS supporter tweeted at 10:34 a.m. Shooting ...,a tweet,0
29,Youth unemployment in minority communities is ...,a gubernatorial debate,2
30,Says Paul Ryan is still endorsing Trump.,a tweet,3
31,"If you look at states that are right to work, ...",a radio talk show,4
32,What (the Obama administration is) going to co...,a campaign ad,0
33,We cut business taxes so today 70 percent of o...,a speech at an Americans for Prosperity Founda...,2
34,Says Mark Pryor votes with Obama 93 percent of...,a debate,2
35,We have a federal government that thinks they ...,a speech at CPAC,3
36,Austin is a city that has basically doubled in...,"his ""State of the City"" address",3
37,The nuclear test conducted in our nation this ...,a released statement,3
38,"In the case of a catastrophic event, the Atlan...",the TV show's season finale,5
39,"Under President George W. Bush, we added $4.9 ...","a town hall meeting in Hudson, N.H.",3

In [27]:
filtered_df = combined_df[['statement', 'label']]

In [28]:
filtered_df.head(10)

                                           statement  label
0  Says the Annies List political group supports ...      0
1  When did the decline of coal start? It started...      1
2  Hillary Clinton agrees with John McCain "by vo...      2
3  Health care reform legislation is likely to ma...      0
4  The economic turnaround started at the end of ...      1
5  The Chicago Bears have had more starting quart...      3
6  Jim Dunnam has not lived in the district he re...      4
7  "I'm the only person on this stage who has wor...      1
8  However, it took $19.5 million in Oregon Lotte...      1
9  Says GOP primary opponents Glenn Grothman and ...      2

In [29]:
def convert_label(x):
    if x in [0, 1]:        # pants-fire, false
        return 0  # False
    elif x in [4, 5]:      # mostly-true, true
        return 1  # True
    else:                  # barely-true, half-true
        return 2  # Misleading

filtered_df['label'] = filtered_df['label'].apply(convert_label)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_21832\972969206.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['label'] = filtered_df['label'].apply(convert_label)

In [30]:
filtered_df.head(30)

                                            statement  label
0   Says the Annies List political group supports ...      0
1   When did the decline of coal start? It started...      0
2   Hillary Clinton agrees with John McCain "by vo...      2
3   Health care reform legislation is likely to ma...      0
4   The economic turnaround started at the end of ...      0
5   The Chicago Bears have had more starting quart...      2
6   Jim Dunnam has not lived in the district he re...      1
7   "I'm the only person on this stage who has wor...      0
8   However, it took $19.5 million in Oregon Lotte...      0
9   Says GOP primary opponents Glenn Grothman and ...      2
10  For the first time in history, the share of th...      2
11  Since 2000, nearly 12 million Americans have s...      0
12  When Mitt Romney was governor of Massachusetts...      0
13  The economy bled $24 billion due to the govern...      2
14  Most of the (Affordable Care Act) has already ...      1
15  In this last election in November, ... 63 perc...      0
16  "McCain opposed a requirement that the governm...      2
17  U.S. Rep. Ron Kind, D-Wis., and his fellow Dem...      1
18  Water rates in Manila, Philippines, were raise...      0
19  Almost 100,000 people left Puerto Rico last year.      2
20  Women and men both are making less when you ad...      0
21  The United States has the highest corporate ta...      2
22  We just had the best year for the auto industr...      2
23  Says Scott Walker favors cutting up to 350,000...      0
24  Says Mitt Romney wants to get rid of Planned P...      1
25              I dont know who (Jonathan Gruber) is.      0
26  Hate crimes against American Muslims and mosqu...      2
27  Rick Perry has never lost an election and rema...      0
28  ISIS supporter tweeted at 10:34 a.m. Shooting ...      0
29  Youth unemployment in minority communities is ...      2

In [31]:
print(filtered_df['label'].value_counts())

label
0    5149
2    4529
1    3158
Name: count, dtype: int64

In [32]:
filtered_df.to_csv("../data/combinedfully_liar.csv", index=False)

Now We working on the Dataset2

In [34]:
df1=pd.read_csv("../data/traindataset2.csv")
df2=pd.read_csv("../data/testdataset2.csv")
df3=pd.read_csv("../data/validatedataset2.csv")

In [35]:
merge_df = pd.concat([df1, df2, df3], ignore_index=True)

# Save to new CSV
merge_df.to_csv("../data/combined_liar.csv", index=False)

print("Files merged successfully!")
print(merge_df.shape)

Files merged successfully!
(8648, 3)

In [36]:
merge_df.head(20)

                                            Statement  True  False
0   74 percent of Republicans support the Affordab...   0.0    1.0
1   Florida's new fingerprint identification syste...   0.0    1.0
2   The nuclear test conducted in our nation this ...   0.5    0.5
3   Texas is growing twice as fast as the rest of ...   1.0    0.0
4   Says the American public overwhelmingly oppose...   1.0    0.0
5   A former Clinton administration official and o...   0.5    0.5
6   On immigration, the president said 22 times, 2...   1.0    0.0
7   A photo of a horse being pulled through a scor...   0.0    1.0
8   Most folks wages havent gone up in over a deca...   1.0    0.0
9   Not a single banker, a CEO from Wall Street, a...   1.0    0.0
10  "America's carbon emissions are being reduced ...   0.5    0.5
11  Not one dime gets added to the deficit because...   0.0    1.0
12  California has seen a 56 percent decline in th...   1.0    0.0
13  The number of killings of citizens by police i...   1.0    0.0
14  In the past 10 years, our (Austin) water rates...   1.0    0.0
15  Paul Ryans Medicare plan could raise future re...   0.5    0.5
16  Says Gov. Scott Walker has made Wisconsin 2nd ...   0.0    1.0
17  Says US Rep Charles Bass wants to privatize So...   0.0    1.0
18  Paul Ryans Medicare plan could raise future re...   1.0    0.0
19  Says presidents George W. Bush and Barack Obam...   0.0    1.0

In [37]:
merge_df.info

<bound method DataFrame.info of                                               Statement  True  False
0     74 percent of Republicans support the Affordab...   0.0    1.0
1     Florida's new fingerprint identification syste...   0.0    1.0
2     The nuclear test conducted in our nation this ...   0.5    0.5
3     Texas is growing twice as fast as the rest of ...   1.0    0.0
4     Says the American public overwhelmingly oppose...   1.0    0.0
...                                                 ...   ...    ...
8643  We spent twice as much per capita for health c...   0.0    1.0
8644  Bill McCollum explained his lack of action on ...   1.0    0.0
8645  Health insurance and medical costs are going d...   0.0    1.0
8646  Says his campaign hasn't accepted corporate PA...   0.5    0.5
8647  "When I ran for Congress, I promised to refuse...   1.0    0.0

[8648 rows x 3 columns]>

In [38]:
def map_label(row):
    if row['True'] == 1.0 and row['False'] == 0.0:
        return 1  # True
    elif row['True'] == 0.0 and row['False'] == 1.0:
        return 0  # False
    elif row['True'] == 0.5 and row['False'] == 0.5:
        return 2  # Misleading
    else:
        return None  # unexpected case

# Apply row-wise
merge_df['label'] = merge_df.apply(map_label, axis=1)

# Check result
print(merge_df['label'].value_counts())

label
2    3188
1    2855
0    2605
Name: count, dtype: int64

In [40]:
merge_df.head(30)

                                            Statement  True  False  label
0   74 percent of Republicans support the Affordab...   0.0    1.0      0
1   Florida's new fingerprint identification syste...   0.0    1.0      0
2   The nuclear test conducted in our nation this ...   0.5    0.5      2
3   Texas is growing twice as fast as the rest of ...   1.0    0.0      1
4   Says the American public overwhelmingly oppose...   1.0    0.0      1
5   A former Clinton administration official and o...   0.5    0.5      2
6   On immigration, the president said 22 times, 2...   1.0    0.0      1
7   A photo of a horse being pulled through a scor...   0.0    1.0      0
8   Most folks wages havent gone up in over a deca...   1.0    0.0      1
9   Not a single banker, a CEO from Wall Street, a...   1.0    0.0      1
10  "America's carbon emissions are being reduced ...   0.5    0.5      2
11  Not one dime gets added to the deficit because...   0.0    1.0      0
12  California has seen a 56 percent decline in th...   1.0    0.0      1
13  The number of killings of citizens by police i...   1.0    0.0      1
14  In the past 10 years, our (Austin) water rates...   1.0    0.0      1
15  Paul Ryans Medicare plan could raise future re...   0.5    0.5      2
16  Says Gov. Scott Walker has made Wisconsin 2nd ...   0.0    1.0      0
17  Says US Rep Charles Bass wants to privatize So...   0.0    1.0      0
18  Paul Ryans Medicare plan could raise future re...   1.0    0.0      1
19  Says presidents George W. Bush and Barack Obam...   0.0    1.0      0
20  Video shows a poll worker committing voter fra...   0.0    1.0      0
21  New provisions of the health care law bar the ...   1.0    0.0      1
22  "Half the workforce in the country may have ju...   0.5    0.5      2
23  Says Joe Radinovich "was cited 30 times for no...   1.0    0.0      1
24  Says she will work to raise the federal minimu...   1.0    0.0      1
25  Bill Nelsons vote for the Affordable Care Act ...   0.0    1.0      0
26  Obamacare takes $500 billion out of Medicare a...   0.5    0.5      2
27  Currently, we're at 36 percent of our children...   1.0    0.0      1
28  Says Donald Trump, in his campaign announcemen...   0.5    0.5      2
29  Says in Katrina, they approved $60 billion wit...   1.0    0.0      1

In [ ]:
# Drop 'True' and 'False' columns
full_df = merge_df.drop(columns=['True', 'False'])
print(full_df.head())

                                           Statement  label
0  74 percent of Republicans support the Affordab...      0
1  Florida's new fingerprint identification syste...      0
2  The nuclear test conducted in our nation this ...      2
3  Texas is growing twice as fast as the rest of ...      1
4  Says the American public overwhelmingly oppose...      1

In [45]:
full1_df = full_df.rename(columns={'Statement': 'title'})
print(full1_df.head(30))

                                                title  label
0   74 percent of Republicans support the Affordab...      0
1   Florida's new fingerprint identification syste...      0
2   The nuclear test conducted in our nation this ...      2
3   Texas is growing twice as fast as the rest of ...      1
4   Says the American public overwhelmingly oppose...      1
5   A former Clinton administration official and o...      2
6   On immigration, the president said 22 times, 2...      1
7   A photo of a horse being pulled through a scor...      0
8   Most folks wages havent gone up in over a deca...      1
9   Not a single banker, a CEO from Wall Street, a...      1
10  "America's carbon emissions are being reduced ...      2
11  Not one dime gets added to the deficit because...      0
12  California has seen a 56 percent decline in th...      1
13  The number of killings of citizens by police i...      1
14  In the past 10 years, our (Austin) water rates...      1
15  Paul Ryans Medicare plan could raise future re...      2
16  Says Gov. Scott Walker has made Wisconsin 2nd ...      0
17  Says US Rep Charles Bass wants to privatize So...      0
18  Paul Ryans Medicare plan could raise future re...      1
19  Says presidents George W. Bush and Barack Obam...      0
20  Video shows a poll worker committing voter fra...      0
21  New provisions of the health care law bar the ...      1
22  "Half the workforce in the country may have ju...      2
23  Says Joe Radinovich "was cited 30 times for no...      1
24  Says she will work to raise the federal minimu...      1
25  Bill Nelsons vote for the Affordable Care Act ...      0
26  Obamacare takes $500 billion out of Medicare a...      2
27  Currently, we're at 36 percent of our children...      1
28  Says Donald Trump, in his campaign announcemen...      2
29  Says in Katrina, they approved $60 billion wit...      1

In [47]:
full1_df.to_csv("../data/Dataset2Liarx.csv",index=False)

In [25]:
import pandas as pd
df=pd.read_csv("../data/combinedfully_liar.csv")

In [27]:
df.columns

Index(['statement', 'label'], dtype='object')

In [28]:
import pandas as pd

def split_statement(text):
    words = text.split()
    
    # First 12 words → title
    title = ' '.join(words[:12])
    
    # Full text → text
    return pd.Series([title, text])

# Apply OUTSIDE the function
df[['title', 'text']] = df['statement'].apply(split_statement)

In [32]:
df.head(10)

,statement,label,title,text
0,Says the Annies List political group supports ...,0,Says the Annies List political group supports ...,Says the Annies List political group supports ...
1,When did the decline of coal start? It started...,0,When did the decline of coal start? It started...,When did the decline of coal start? It started...
2,"Hillary Clinton agrees with John McCain ""by vo...",2,"Hillary Clinton agrees with John McCain ""by vo...","Hillary Clinton agrees with John McCain ""by vo..."
3,Health care reform legislation is likely to ma...,0,Health care reform legislation is likely to ma...,Health care reform legislation is likely to ma...
4,The economic turnaround started at the end of ...,0,The economic turnaround started at the end of ...,The economic turnaround started at the end of ...
5,The Chicago Bears have had more starting quart...,2,The Chicago Bears have had more starting quart...,The Chicago Bears have had more starting quart...
6,Jim Dunnam has not lived in the district he re...,1,Jim Dunnam has not lived in the district he re...,Jim Dunnam has not lived in the district he re...
7,"""I'm the only person on this stage who has wor...",0,"""I'm the only person on this stage who has wor...","""I'm the only person on this stage who has wor..."
8,"However, it took $19.5 million in Oregon Lotte...",0,"However, it took $19.5 million in Oregon Lotte...","However, it took $19.5 million in Oregon Lotte..."
9,Says GOP primary opponents Glenn Grothman and ...,2,Says GOP primary opponents Glenn Grothman and ...,Says GOP primary opponents Glenn Grothman and ...

In [33]:
df1=df.drop("statement",axis=1)

In [34]:
# Reorder columns: statement → text → label
df2 = df1[['title', 'text', 'label']]

df2.head(10)

,title,text,label
0,Says the Annies List political group supports ...,Says the Annies List political group supports ...,0
1,When did the decline of coal start? It started...,When did the decline of coal start? It started...,0
2,"Hillary Clinton agrees with John McCain ""by vo...","Hillary Clinton agrees with John McCain ""by vo...",2
3,Health care reform legislation is likely to ma...,Health care reform legislation is likely to ma...,0
4,The economic turnaround started at the end of ...,The economic turnaround started at the end of ...,0
5,The Chicago Bears have had more starting quart...,The Chicago Bears have had more starting quart...,2
6,Jim Dunnam has not lived in the district he re...,Jim Dunnam has not lived in the district he re...,1
7,"""I'm the only person on this stage who has wor...","""I'm the only person on this stage who has wor...",0
8,"However, it took $19.5 million in Oregon Lotte...","However, it took $19.5 million in Oregon Lotte...",0
9,Says GOP primary opponents Glenn Grothman and ...,Says GOP primary opponents Glenn Grothman and ...,2

In [36]:
print("Duplicate titles:", df2['title'].duplicated().sum())

Duplicate titles: 27

In [38]:
# Remove all duplicate rows based on 'statement'
df3 = df2.drop_duplicates(subset=['title']).reset_index(drop=True)

# Verify
print("Remaining rows:", df3.shape)
print("Duplicate titles after removal:", df3['title'].duplicated().sum())

Remaining rows: (12809, 3)
Duplicate titles after removal: 0

In [39]:
df3.head(10)

,title,text,label
0,Says the Annies List political group supports ...,Says the Annies List political group supports ...,0
1,When did the decline of coal start? It started...,When did the decline of coal start? It started...,0
2,"Hillary Clinton agrees with John McCain ""by vo...","Hillary Clinton agrees with John McCain ""by vo...",2
3,Health care reform legislation is likely to ma...,Health care reform legislation is likely to ma...,0
4,The economic turnaround started at the end of ...,The economic turnaround started at the end of ...,0
5,The Chicago Bears have had more starting quart...,The Chicago Bears have had more starting quart...,2
6,Jim Dunnam has not lived in the district he re...,Jim Dunnam has not lived in the district he re...,1
7,"""I'm the only person on this stage who has wor...","""I'm the only person on this stage who has wor...",0
8,"However, it took $19.5 million in Oregon Lotte...","However, it took $19.5 million in Oregon Lotte...",0
9,Says GOP primary opponents Glenn Grothman and ...,Says GOP primary opponents Glenn Grothman and ...,2

In [40]:
df3.to_csv("../data/combinedfully_liar123.csv",index=False)

In [2]:
import pandas as pd
df=pd.read_csv("../data/NewDatasetliarx.csv")
df.head(10)

,statement,text,label
0,74 percent of Republicans support the Affordab...,74 percent of Republicans support the Affordab...,0
1,Florida's new fingerprint identification syste...,Florida's new fingerprint identification syste...,0
2,The nuclear test conducted in our nation this ...,The nuclear test conducted in our nation this ...,2
3,Texas is growing twice as fast as the rest of ...,Texas is growing twice as fast as the rest of ...,1
4,Says the American public overwhelmingly oppose...,Says the American public overwhelmingly oppose...,1
5,A former Clinton administration official and o...,A former Clinton administration official and o...,2
6,"On immigration, the president said 22 times, 2...","On immigration, the president said 22 times, 2...",1
7,A photo of a horse being pulled through a scor...,A photo of a horse being pulled through a scor...,0
8,Most folks wages havent gone up in over a deca...,Most folks wages havent gone up in over a deca...,1
9,"Not a single banker, a CEO from Wall Street, a...","Not a single banker, a CEO from Wall Street, a...",1

In [4]:
df1=df.rename(columns={"statement":"title"})
df1.head(10)

,title,text,label
0,74 percent of Republicans support the Affordab...,74 percent of Republicans support the Affordab...,0
1,Florida's new fingerprint identification syste...,Florida's new fingerprint identification syste...,0
2,The nuclear test conducted in our nation this ...,The nuclear test conducted in our nation this ...,2
3,Texas is growing twice as fast as the rest of ...,Texas is growing twice as fast as the rest of ...,1
4,Says the American public overwhelmingly oppose...,Says the American public overwhelmingly oppose...,1
5,A former Clinton administration official and o...,A former Clinton administration official and o...,2
6,"On immigration, the president said 22 times, 2...","On immigration, the president said 22 times, 2...",1
7,A photo of a horse being pulled through a scor...,A photo of a horse being pulled through a scor...,0
8,Most folks wages havent gone up in over a deca...,Most folks wages havent gone up in over a deca...,1
9,"Not a single banker, a CEO from Wall Street, a...","Not a single banker, a CEO from Wall Street, a...",1

In [5]:
df1.to_csv("../data/finaldatasets/NewDatasetliarx1.csv",index=False)