In [1]:
import pandas as pd 
import numpy

In [2]:
df=pd.read_csv("../data/Final_data.csv")
df.head(10)

,Unnamed: 0,title,text,Label
0,0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",0
1,1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,1
2,2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,1
3,3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",0
4,4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",1
5,5,Paul Ryan Responds To Dem’s Sit-In On Gun Con...,"On Wednesday, Democrats took a powerful stance...",0
6,6,AWESOME! DIAMOND AND SILK Rip Into The Press: ...,President Trump s rally in FL on Saturday was ...,0
7,7,STAND UP AND CHEER! UKIP Party Leader SLAMS Ge...,He s been Europe s version of the outspoken Te...,0
8,8,North Korea shows no sign it is serious about ...,WASHINGTON (Reuters) - The State Department sa...,1
9,9,Trump signals willingness to raise U.S. minimu...,(This version of the story corrects the figur...,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  44898 non-null  int64
 1   title       44898 non-null  object
 2   text        44898 non-null  object
 3   Label       44898 non-null  int64
dtypes: int64(2), object(2)
memory usage: 1.4+ MB

In [4]:
import re
def clean_text(text):
    text = str(text).lower()  # lowercase everything
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # remove URLs
    text = re.sub(r'\W', ' ', text)  # remove punctuation
    text = re.sub(r'\s+', ' ', text)  # remove extra spaces
    return text.strip()  # remove leading/trailing spaces

# Apply cleaning to the 'text' column
df['text'] = df['text'].apply(clean_text)

In [5]:
df = df[df['text'] != '']
df.head(30)

,Unnamed: 0,title,text,Label
0,0,Ben Stein Calls Out 9th Circuit Court: Committ...,21st century wire says ben stein reputable pro...,0
1,1,Trump drops Steve Bannon from National Securit...,washington reuters u s president donald trump ...,1
2,2,Puerto Rico expects U.S. to lift Jones Act shi...,reuters puerto rico governor ricardo rossello ...,1
3,3,OOPS: Trump Just Accidentally Confirmed He Le...,on monday donald trump once again embarrassed ...,0
4,4,Donald Trump heads for Scotland to reopen a go...,glasgow scotland reuters most u s presidential...,1
5,5,Paul Ryan Responds To Dem’s Sit-In On Gun Con...,on wednesday democrats took a powerful stance ...,0
6,6,AWESOME! DIAMOND AND SILK Rip Into The Press: ...,president trump s rally in fl on saturday was ...,0
7,7,STAND UP AND CHEER! UKIP Party Leader SLAMS Ge...,he s been europe s version of the outspoken te...,0
8,8,North Korea shows no sign it is serious about ...,washington reuters the state department said w...,1
9,9,Trump signals willingness to raise U.S. minimu...,this version of the story corrects the figure ...,1
10,10,New Jersey's Christie mulls run to lead Republ...,washington reuters new jersey governor chris c...,1
12,12,"France, Germany want Iran to reverse ballistic...",paris reuters france and germany agree that ir...,1
13,13,Aide to EU Commission head tweets picture of w...,brussels reuters martin selmayr a top aide to ...,1
14,14,"Trump Issues Warning To “200,000 man army” Tha...",before you blame trump for not being compassio...,0
15,15,U.S. gives Laos extra $90 million to help clea...,vientiane reuters the united states announced ...,1
16,16,JUDGE DECLARES BABY NAME “Illegal” To Prevent ...,does a judge have the right to determine what ...,0
17,17,Paul Ryan Takes A Monumentally HUMILIATING Ph...,politicians are all about photo ops this is es...,0
18,18,"Republicans Dine With Trump, Then Try To Rail...",republicans are once again putting their party...,0
19,19,U.S. House panel offers alternative to retirem...,washington reuters legislation to bypass the u...,1
20,20,"This New Poll Is TERRIFIC News For Democrats,...",while democratic and republicans candidates co...,0
21,21,BOOM! KELLYANNE CONWAY Schools CNN’s Anderson ...,kellyanne conway went at it with anderson coop...,0
22,22,"Trump, tech tycoons talk overhaul of H1B visas",new york san francisco reuters president elect...,1
23,23,"Governor of Yemen's interim capital resigns, a...",aden reuters the governor of president abd rab...,1
24,24,"U.S. military can withstand the sage grouse, l...",washington reuters efforts to protect the grea...,1
25,25,It Looks Like The Trump Campaign Just Got Thi...,while donald trump accuses hillary clinton of ...,0
26,26,Asian American Organizations RAIN HELL Upon F...,asian americans are pissed off after fox news ...,0
27,27,OUCH! BUSH “BESTIE” Goes Against GOP Elites…EN...,that s gonna leave a mark former vice presiden...,0
28,28,Carter says defense relationship with Philippi...,london reuters u s secretary of defense ash ca...,1
29,29,"Factbox - Battle for Raqqa, Islamic State's Sy...",beirut reuters the battle for the city of raqq...,1
30,30,Images suggest North Korea 'aggressive' work o...,washington reuters satellite images taken this...,1

In [8]:
df.drop("Unnamed: 0",axis=1)
df.head(30)

,Unnamed: 0,title,text,Label
0,0,Ben Stein Calls Out 9th Circuit Court: Committ...,21st century wire says ben stein reputable pro...,0
1,1,Trump drops Steve Bannon from National Securit...,washington reuters u s president donald trump ...,1
2,2,Puerto Rico expects U.S. to lift Jones Act shi...,reuters puerto rico governor ricardo rossello ...,1
3,3,OOPS: Trump Just Accidentally Confirmed He Le...,on monday donald trump once again embarrassed ...,0
4,4,Donald Trump heads for Scotland to reopen a go...,glasgow scotland reuters most u s presidential...,1
5,5,Paul Ryan Responds To Dem’s Sit-In On Gun Con...,on wednesday democrats took a powerful stance ...,0
6,6,AWESOME! DIAMOND AND SILK Rip Into The Press: ...,president trump s rally in fl on saturday was ...,0
7,7,STAND UP AND CHEER! UKIP Party Leader SLAMS Ge...,he s been europe s version of the outspoken te...,0
8,8,North Korea shows no sign it is serious about ...,washington reuters the state department said w...,1
9,9,Trump signals willingness to raise U.S. minimu...,this version of the story corrects the figure ...,1
10,10,New Jersey's Christie mulls run to lead Republ...,washington reuters new jersey governor chris c...,1
12,12,"France, Germany want Iran to reverse ballistic...",paris reuters france and germany agree that ir...,1
13,13,Aide to EU Commission head tweets picture of w...,brussels reuters martin selmayr a top aide to ...,1
14,14,"Trump Issues Warning To “200,000 man army” Tha...",before you blame trump for not being compassio...,0
15,15,U.S. gives Laos extra $90 million to help clea...,vientiane reuters the united states announced ...,1
16,16,JUDGE DECLARES BABY NAME “Illegal” To Prevent ...,does a judge have the right to determine what ...,0
17,17,Paul Ryan Takes A Monumentally HUMILIATING Ph...,politicians are all about photo ops this is es...,0
18,18,"Republicans Dine With Trump, Then Try To Rail...",republicans are once again putting their party...,0
19,19,U.S. House panel offers alternative to retirem...,washington reuters legislation to bypass the u...,1
20,20,"This New Poll Is TERRIFIC News For Democrats,...",while democratic and republicans candidates co...,0
21,21,BOOM! KELLYANNE CONWAY Schools CNN’s Anderson ...,kellyanne conway went at it with anderson coop...,0
22,22,"Trump, tech tycoons talk overhaul of H1B visas",new york san francisco reuters president elect...,1
23,23,"Governor of Yemen's interim capital resigns, a...",aden reuters the governor of president abd rab...,1
24,24,"U.S. military can withstand the sage grouse, l...",washington reuters efforts to protect the grea...,1
25,25,It Looks Like The Trump Campaign Just Got Thi...,while donald trump accuses hillary clinton of ...,0
26,26,Asian American Organizations RAIN HELL Upon F...,asian americans are pissed off after fox news ...,0
27,27,OUCH! BUSH “BESTIE” Goes Against GOP Elites…EN...,that s gonna leave a mark former vice presiden...,0
28,28,Carter says defense relationship with Philippi...,london reuters u s secretary of defense ash ca...,1
29,29,"Factbox - Battle for Raqqa, Islamic State's Sy...",beirut reuters the battle for the city of raqq...,1
30,30,Images suggest North Korea 'aggressive' work o...,washington reuters satellite images taken this...,1

In [ ]:
df.to_csv("../data/fullfinal.csv")

In [4]:
import pandas as pd

In [3]:
df=pd.read_csv("../data/Now1_Fullfinal.csv")
df.head(10)

,Unnamed: 0.1,Unnamed: 0,title,text,label
0,0,32915,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,1,902,reporter breaks down what we know after rubio ...,CNN's Matthew Chance has more details. 2:46 Ã¢...,1
2,2,37652,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
3,3,59295,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
4,4,41371,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
5,5,21743,BLACK BOSTON COP Taunted By Black Woman: “You ...,we ve seen an escalation in violence against p...,0
6,6,28638,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
7,7,12136,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
8,8,2780,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
9,9,35962,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1

In [9]:
df1=df.drop("Unnamed: 0.1",axis=1)
df1.head(10)

,Unnamed: 0,title,text,label
0,32915,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,902,reporter breaks down what we know after rubio ...,CNN's Matthew Chance has more details. 2:46 Ã¢...,1
2,37652,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
3,59295,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
4,41371,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
5,21743,BLACK BOSTON COP Taunted By Black Woman: “You ...,we ve seen an escalation in violence against p...,0
6,28638,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
7,12136,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
8,2780,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
9,35962,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1

In [11]:
df2=df1.drop("Unnamed: 0",axis=1)
df2.head(10)

,title,text,label
0,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,reporter breaks down what we know after rubio ...,CNN's Matthew Chance has more details. 2:46 Ã¢...,1
2,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
3,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
4,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
5,BLACK BOSTON COP Taunted By Black Woman: “You ...,we ve seen an escalation in violence against p...,0
6,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
7,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
8,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
9,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1

In [12]:
df2.info

<bound method DataFrame.info of                                                    title  \
0      N.C. governor signs bill repealing Charlotte t...
1      reporter breaks down what we know after rubio ...
2      Clinton, Trump clash over economy in final cam...
3       Chris Wallace Gets NC Governor To Admit That ...
4       Pastor Shot And Killed In The Middle Of Churc...
...                                                  ...
63545  HILLARY CAUGHT IN THE ACT OF Breaking The Law ...
63546  Trump recognition of Jerusalem as Israeli capi...
63547  Road That Smells Faintly Sweet Only in the Ear...
63548  clinton to meet with house democrats on wednes...
63549  Trump handling of security information at Mar-...

                                                    text  label
0      winston salem n c reuters north carolina s gov...      1
1      CNN's Matthew Chance has more details. 2:46 Ã¢...      1
2      cleveland hershey pa reuters democrat hillary ...      1
3      fox host chris wallace pinned bigoted north ca...      0
4      a routine church service at the st peter s mis...      0
...                                                  ...    ...
63545  imagine what it must be like to be one of the ...      0
63546  cairo reuters any move by the united states to...      1
63547                       Dawn commuters noticed aroma      0
63548  washington reuters presidential candidate hill...      0
63549  washington reuters president donald trump s ha...      1

[63550 rows x 3 columns]>

In [14]:
import chardet

with open("../data/Now1_Fullfinal.csv", "rb") as f:
    result = chardet.detect(f.read())

print(result)

{'encoding': 'utf-8', 'confidence': 0.8014535, 'language': 'en', 'mime_type': 'text/plain'}

In [17]:
df3 = df2.apply(lambda x: x.encode('latin1').decode('utf-8') if isinstance(x, str) else x)

In [26]:
def fix_mojibake(text):
    if isinstance(text, str):
        try:
            for _ in range(2):  # run multiple times
                text = text.encode('latin1').decode('utf-8')
        except:
            pass
    return text

In [27]:
for col in df.select_dtypes(include='object').columns:
    df3[col] = df3[col].apply(fix_mojibake)

In [28]:
def clean_text(text):
    if isinstance(text, str):
        try:
            for _ in range(2):
                text = text.encode('latin1').decode('utf-8')
        except:
            pass
        
        text = text.replace('“', '"').replace('”', '"')
        text = text.replace('’', "'")
    return text

for col in df.select_dtypes(include='object').columns:
    df3[col] = df3[col].apply(clean_text)

In [29]:
df3.to_csv("../data/final.csv")

In [43]:
df=pd.read_csv("../data/final3.csv")
df.head(40)

,Unnamed: 0,title,text,label
0,0,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,1,reporter breaks down what we know after rubio ...,CNN's Matthew Chance has more details. 2:46 • ...,1
2,2,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
3,3,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
4,4,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
5,5,"BLACK BOSTON COP Taunted By Black Woman: ""You ...",we ve seen an escalation in violence against p...,0
6,6,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
7,7,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
8,8,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
9,9,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1
10,10,Forest Wind Generates Musical Arcs Above Tree ...,Air flows create shimmering sound waves visibl...,0
11,11,N.J. Governor Chris Christie accosts heckler i...,new york reuters new jersey governor chris chr...,1
12,12,Boiler Room EP #109 – It's a Wonderfull Life,tune in to the alternate current radio network...,0
13,13,Republicans join push to lift secrecy around m...,washington reuters prominent republican senato...,1
14,14,UNPRECEDENTED: New York Times To Run 30 Sec Ad...,the new york times is set to launch a televisi...,0
15,15,MISLEADING MAINSTREAM MEDIA Is Pushing False N...,here is michigan elector michael banerian tell...,0
16,16,Right-Wing Radio Host Regrets That Conservati...,as donald trump continues to be showered with ...,0
17,17,Donald Trump's Son Bashes His Father's Campai...,if you ve never had to suffer through any of t...,0
18,18,New York governor calls for amending state con...,new york reuters new york governor andrew cuom...,1
19,19,stockholm study: us & europe top arms trade gl...,21st century wire says according to the stockh...,1
20,20,FORGET ABOUT RUSSIA…Here's What's REALLY Affec...,in march 2015 only months after detroit emerge...,0
21,21,Homeless Man Dies Next To 4-STAR HOTEL…Your Bl...,liberal compassion this story is a perfect exa...,0
22,22,"Russian, Iranian presidents discuss Iraqi Kurd...",london reuters russian president putin and his...,1
23,23,Fox News Mocked Into Oblivion After This F*ck...,in a desperate attempt to make steve bannon se...,0
24,24,U.S. officials working to restore public trust...,washington reuters u s attorney general lorett...,1
25,25,U.S. visas issued to citizens of Trump travel ...,washington reuters the united states issued ab...,1
26,26,nyt publishes another misleading headlines—we ...,The article in question has now changed the he...,1
27,27,trudeau confronts canada's failure of indigeno...,ottawa reuters prime minister justin trudeau o...,0
28,28,"leon chlon, phd",... today. You will also pay the triple lock o...,1
29,29,U.S. House lawmaker to release revamped Dodd-F...,washington reuters the head of the u s house o...,1
30,30,"Trump chooses congressman, former SEAL Zinke a...",washington reuters president elect donald trum...,1
31,31,STATUE OF LIBERTY AS A MUSLIM? Congressman Spa...,here we go again another student art contest t...,0
32,32,LIBERAL LUNATIC CHRIS MATTHEWS Scolded By Pier...,who knew former cnn anchor piers morgan would ...,0
33,33,Mexico enshrines army's role in drug war with ...,mexico city reuters mexico s congress on frida...,1
34,34,BREAKING VIDEO: Clinton Can't Explain Discrepa...,lying liar pants continues to fudge and hedge ...,0
35,35,"Battered U.S. coal industry hopes for Trump, p...",washington reuters republican presidential nom...,1
36,36,"Trump, McConnell say they remain united on sha...",washington reuters u s president donald trump ...,1
37,37,Boiler Room EP #114 – Psychos In The Compromis...,tune in to the alternate current radio network...,0
38,38,BOOM! FORMER SHERIFF DAVID CLARKE Has A New Ni...,fox news the new york times reported earlier t...,0
39,39,europe hopes for clinton win for more deals wi...,europe hopes for clinton win for more deals wi...,1

In [44]:
df7=df.drop("Unnamed: 0", axis=1)
df7.head(20)

,title,text,label
0,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,reporter breaks down what we know after rubio ...,CNN's Matthew Chance has more details. 2:46 • ...,1
2,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
3,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
4,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
5,"BLACK BOSTON COP Taunted By Black Woman: ""You ...",we ve seen an escalation in violence against p...,0
6,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
7,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
8,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
9,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1
10,Forest Wind Generates Musical Arcs Above Tree ...,Air flows create shimmering sound waves visibl...,0
11,N.J. Governor Chris Christie accosts heckler i...,new york reuters new jersey governor chris chr...,1
12,Boiler Room EP #109 – It's a Wonderfull Life,tune in to the alternate current radio network...,0
13,Republicans join push to lift secrecy around m...,washington reuters prominent republican senato...,1
14,UNPRECEDENTED: New York Times To Run 30 Sec Ad...,the new york times is set to launch a televisi...,0
15,MISLEADING MAINSTREAM MEDIA Is Pushing False N...,here is michigan elector michael banerian tell...,0
16,Right-Wing Radio Host Regrets That Conservati...,as donald trump continues to be showered with ...,0
17,Donald Trump's Son Bashes His Father's Campai...,if you ve never had to suffer through any of t...,0
18,New York governor calls for amending state con...,new york reuters new york governor andrew cuom...,1
19,stockholm study: us & europe top arms trade gl...,21st century wire says according to the stockh...,1

In [45]:
df7.columns

Index(['title', 'text', 'label'], dtype='object')

In [46]:
corrupted_rows = df[df['title'].str.contains(r'Ã|Â|â', na=False)]
print(corrupted_rows.head(10))
print("Total corrupted rows:", corrupted_rows.shape[0])

Empty DataFrame
Columns: [Unnamed: 0, title, text, label]
Index: []
Total corrupted rows: 0

In [ ]:
import re

def is_corrupted(text):                         # very important pipeline for suspecious data. this will remove the corrupted data, use this cell next and then next
    if not isinstance(text, str):
        return False

    # 1. Typical mojibake patterns
    if re.search(r'Ã.|Â.|â.', text):
        return True

    # 2. Too many suspicious characters
    suspicious = sum(1 for c in text if ord(c) in range(128, 256))
    if suspicious > len(text) * 0.2:  # >20% suspicious chars
        return True

    # 3. Repeated weird sequences like Ã°Â
    if re.search(r'(Ã.|Â.|â.){2,}', text):
        return True

    return False

In [59]:
mask = df7['title'].apply(is_corrupted)

corrupted_rows = df7[mask]

print("Total corrupted rows:", corrupted_rows.shape[0])
print(corrupted_rows)

Total corrupted rows: 33
                                                   title  \
313    ðñññð¸ðµ ð´ññð·ññ ðð¾ð½ð°ð»ñð´ð° ð¢ñ...
1263   ðð±ð°ð¼ð° ð¿ñð¸ð·ð²ð°ð» ð¢ñññð¸ñ ðºð¾ð¾ñ...
1676   ø­ùùùùù: 44 ø¹ùùùø© ùøµù ùù ùø¨ù...
5041   ð ðð¾ð»ð³ðµ ð½ð°ñð»ð¸ ð°ð¼ðµñð¸ðºð°ð½ñðºð...
6623   ðð±ð°ð¼ð° ñð½ð¸ññð¾ð¶ð¸ð» ð°ð¼ðµñð¸ðºð°ð½...
7540   ðð°ð½ð°ð´ñðºð°ñ ð´ðµð»ðµð³ð°ñð¸ñ ð½ðµ ð¿ñ...
8841   ð¡ð°ð½ðºñð¸ð¸ ð¿ñð¾ñð¸ð² ð ð¾ññð¸ð¸ - ð¾ñ...
9165   ðð¡ ð½ð°ð¼ðµñðµð½ ñð°ññð¸ñð¸ññ ñð°ð½ð...
9896   ð¤ð»ðµñðºð¸ ð±ñð´ññðµð³ð¾: ð£ñðµð½ñðµ ð¾...
10470  ðññð¸ð½ ð²ññðºð°ð·ð°ð» ð²ñðµ, ññð¾ ð¾ð...
10564  ð¡ñð°ð»ð° ð¸ð·ð²ðµññð½ð° ð²ð¾ð·ð¼ð¾ð¶ð½ð°ñ...
13641  ð£ñðµð½ñðµ ð¿ñð¸ð±ð»ð¸ð·ð¸ð»ð¸ññ ðº ñð°ð...
15907  "ð§ðµð¼ ð±ð»ð¸ð¶ðµ ð¼ñ ðº ð²ð·ññð¸ñ ðð»ðµ...
17265     ðñð¾ ð»ñð±ð¸ñ ð¡ñð¸ð²ðµð½ð° ð¡ð¸ð³ð°ð»ð°?
20781  ø§ùø¬ùø´ ø§ùùùùù ùùø§ø¬ù ùùø§øª ø§...
23418  ð©ð¸ñ ðð²ññð°ñð°: ñð´ð°ññññ ð»ð¸ ð·ð...
25337   ð¥ð²ð°ñð¸ñ ð¿ð¾ð¿ññð¾ðº! ðñð¾ññð¾ ð±ðµð¹
27909  ðñð¾ð²ð°ð» ð·ð° ð¿ñð¾ð²ð°ð»ð¾ð¼: ð ð¡ð¨ð ...
28317  ðñðµð·ð¸ð´ðµð½ñ ðññð¸ð½ ð¾ñð²ðµñð¸ð» ð...
28860  ðð¾ð²ð°ñ ððµð»ð°ð½ð´ð¸ñ ð·ð°ñð²ð¸ð»ð° ð¾ ...
31056  comment on hillary clinton campaign logo has a...
33942  ðð°ð¼ðµñññ ð»ð¸ ð² ð ð¾ññð¸ð¸ ð¾ñð¼ðµð½...
34909  ðð¼ðµñð¸ðºð°ð½ð¾-ðºð¾ñðµð¹ñðºð¸ðµ ð¾ñð½ð¾...
36911  ð­ðºð¾ð»ð¾ð³ð¸: ð§ð¸ñð»ð¾ ð¿ð¾ð·ð²ð¾ð½ð¾ñð½ñ...
41317  ø§ùùøºø§ø±ø¨ø© ùø°ùùùù ø§ùø¹ø§ùù ùù...
42366  ððµññð°ñðµð»ð¸ ð¸ð· ððµð½ñð°ð³ð¾ð½ð°: ðº...
43335  ùù øªùøªø²ù ùø§ø´ùø·ù ø¨ùùø§ø¹ø¯ ø§ù...
45362  ðð°ñðµð¼ ñðºñð°ð¸ð½ñðºð¾ð¼ñ ð¾ð»ð¸ð³ð°ñ...
46405  ð ððð ð¾ð¿ñð¾ð²ðµñð³ð»ð¸, ññð¾ ñð°ð·ñ...
46484  ðð¾ðµð·ð´ ð¡ð°ð¿ñð°ð½ ð·ð°ð´ðµñð¶ð°ð»ññ ð...
46496  ð¢ð°ð¸ð»ð°ð½ð´ ð¼ðµð¶ð´ñ ð¢ð¢ð ð¸ ððð­ð¡ |...
57504  ùø²ø§ø±ø© ø§ùø®ø§ø±ø¬ùø© ø§ùø£ùùø±ùùø©...
63371  ððµ ð´ð°ð´ð¸ð¼ ñð¾ññð¸ð¹ñðºð¸ð¼ ñð¾ð±ð¾ñ...

                                                    text  label
313                                                   45      1
1263                27 2016 03 13 telegram telegram join      1
1676                26 44 24 19 18 3 3 1 851 4 rt arabic      1
5041   27 2016 01 21 kellicottia bostoniensis telegra...      1
6623                                         wallmart 13      1
7540   27 2016 02 47 27 ceta ceta telegram telegram join      1
8841   0 3 fotodom ru dp bloomberg swift pravda ru pr...      1
9165   0 0 pravda ru wall street journal 200 70 pravd...      1
9896   0 0 science advances dvd blu ray blu ray pravd...      1
10470                                 0 7 xiii pravda ru      1
10564                    23 10 1 279 61 162 31 pravda ru      1
13641  0 0 eurekalert nmn nmn nmn 150 1000 alphabet i...      1
15907  0 0 afp reuters pravda ru 2015 2011 220 pravda ru      1
17265                                            1990 90      1
20781  26 10 2016 17 52 gmt a 3 19 reuters mohamed al...      1
23418                                               2012      1
25337                              nbc news 200 146 62 2      1
27909  0 3 pravda ru associated press 51 iii booz all...      1
28317                 0 14 kremlin ru 200 xiii pravda ru      1
28860            27 2016 07 10 rt telegram telegram join      1
31056  adobochron 1 comment san francisco california ...      1
33942  25 0 0 ap 2014 pravda ru pravda ru 5 10 2 3 pr...      1
34909  28 5 f 16 patriot 16 3 9 10 o thaad 14 100 9 2...      1
36911  0 0 42 81 38 36 3 706 67 pravda ru 5 5 health ...      1
41317   26 10 2016 13 27 gmt challenger 6 4 6 3 lenta ru      1
42366  27 2016 00 10 c 90 58 rt cg x dod cg x cg x 90...      1
43335  26 10 2016 12 20 gmt 25 18 22 2016 27 rt 20 27...      1
45362  0 2 fotodom ru midland group 1 pravda ru 2014 ...      1
46405  0 3 fotodom ru 13 26 16 16 26 13 300 gelandewa...      1
46484  0 0 pravda ru 2 5 3 2 5 3 778 22 21 22 45 22 4...      1
46496  4 2016 25 2012 20 14 150 22 2 2016 2 2016 2016...      1
57504            26 2016 fran ais espa ol t rk e deutsch      1
63371                                    19 2016 it 4 12      1

In [60]:
df8 = df[~mask]

C:\Users\ahmad\AppData\Local\Temp\ipykernel_18380\1383047789.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df8 = df[~mask]

In [61]:
df8.to_csv("../data/final5.csv")

In [62]:
df8.info

<bound method DataFrame.info of        Unnamed: 0                                              title  \
0               0  N.C. governor signs bill repealing Charlotte t...
1               1  reporter breaks down what we know after rubio ...
2               2  Clinton, Trump clash over economy in final cam...
3               3   Chris Wallace Gets NC Governor To Admit That ...
4               4   Pastor Shot And Killed In The Middle Of Churc...
...           ...                                                ...
63486       63545  HILLARY CAUGHT IN THE ACT OF Breaking The Law ...
63487       63546  Trump recognition of Jerusalem as Israeli capi...
63488       63547  Road That Smells Faintly Sweet Only in the Ear...
63489       63548  clinton to meet with house democrats on wednes...
63490       63549  Trump handling of security information at Mar-...

                                                    text  label
0      winston salem n c reuters north carolina s gov...      1
1      CNN's Matthew Chance has more details. 2:46 • ...      1
2      cleveland hershey pa reuters democrat hillary ...      1
3      fox host chris wallace pinned bigoted north ca...      0
4      a routine church service at the st peter s mis...      0
...                                                  ...    ...
63486  imagine what it must be like to be one of the ...      0
63487  cairo reuters any move by the united states to...      1
63488                       Dawn commuters noticed aroma      0
63489  washington reuters presidential candidate hill...      0
63490  washington reuters president donald trump s ha...      1

[63458 rows x 4 columns]>

In [20]:
pattern = r'Ã|Â|â'

mask = df.select_dtypes(include='object').apply(
    lambda col: col.str.contains(pattern, na=False)
)
df8 = df7[~mask.any(axis=1)]
print("Remaining rows:", df8.shape[0])

Remaining rows: 63491

In [10]:
def fix_mojibake(text):
    if not isinstance(text, str):
        return text
    
    for _ in range(5):  # multiple passes for heavy corruption
        try:
            new_text = text.encode('latin1').decode('utf-8')
            if new_text == text:
                break
            text = new_text
        except:
            break
    return text

In [11]:
for col in df.select_dtypes(include='object').columns:
    df7[col] = df7[col].apply(fix_mojibake)

In [1]:
import pandas as pd
df=pd.read_csv("../data/previous.csv")
df.head(10)

,title,text,label
0,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,reporter breaks down what we know after rubio ...,CNN's Matthew Chance has more details. 2:46 • ...,1
2,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
3,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
4,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
5,"BLACK BOSTON COP Taunted By Black Woman: ""You ...",we ve seen an escalation in violence against p...,0
6,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
7,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
8,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
9,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1

In [2]:
df.head(10)

,title,text,label
0,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,reporter breaks down what we know after rubio ...,CNN's Matthew Chance has more details. 2:46 • ...,1
2,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
3,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
4,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
5,"BLACK BOSTON COP Taunted By Black Woman: ""You ...",we ve seen an escalation in violence against p...,0
6,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
7,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
8,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
9,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1

In [3]:
# Find rows with non-ASCII (weird encoded) characters
mask = df['text'].str.contains(r'[^\x00-\x7F]', regex=True, na=False)

# Count them
count = mask.sum()
print("Total problematic rows:", count)
print(df[mask]['title'].head(40))

Total problematic rows: 1352
1       reporter breaks down what we know after rubio ...
35      updates | united nations office for the coordi...
45                        china technology news & updates
66           misinformation news - today's latest updates
72      the latest headlines - as zelenskyy's top advi...
105     suspect with possible us government ties trigg...
157     California lawmakers hire Holder for fights wi...
200     govtrack.us: tracking the u.s. congress and th...
204     biggest tv, film and celebrity controversies o...
216                               science advances | aaas
248                               homeland security: home
338                     pressroom | governor kathy hochul
371     10 years since 'viral thanksgiving text' spark...
406     breaking news, video and the latest top storie...
408     axios - breaking news, u.s. news and politics,...
411        trending topics on social media 2024: top tips
554     ++xxx+videos+!! latest couple viral video on i...
611     school assembly headlines for november 29: key...
637         latest u.s. news | top headlines from the usa
665                         breaking & latest sports news
694                                us politics - bbc news
761      abc news - breaking news, latest news and videos
811                 news | today's latest from al jazeera
912     scientific breakthroughs | national institutes...
987         latest u.s. news | top headlines from the usa
994      top 15 social media trends for marketers in 2025
1067          evaluating news resources - research guides
1156    yahoo news: latest and breaking news, headline...
1164    8 tips for finding new and emerging trends on ...
1201    top 15 breakthrough discoveries that will chan...
1254    Trump's Treasury nominee Mnuchin pledges to di...
1314                                             politics
1484    California Democrats propose series of infrast...
1501     abc news - breaking news, latest news and videos
1546    top 10 social media trends: what you need to k...
1603    aol.com: news, politics, sports, mail & latest...
1728                         federal reserve board - home
1746        latest u.s. news | top headlines from the usa
1752                   global & u.s. economy news updates
1797                                      technology news
Name: title, dtype: object

In [4]:
# Remove rows containing non-ASCII (weird encoded) characters
mask = df['text'].str.contains(r'[^\x00-\x7F]', regex=True, na=False)

final_df = df[~mask].reset_index(drop=True)              # this is used to remove the data which contain (â€) this type of data so i removed these all rows.this character is comma which is not recognized

print("Remaining rows:", final_df.shape)

Remaining rows: (52507, 3)

In [9]:
import re
def shorten_text(text):
    if pd.isna(text):
        return text
    sentences = re.split(r'(?<=[.!?]) +', text)
    short = ' '.join(sentences[:3])
    return ' '.join(short.split()[:60])  # max 60 words
final_df['text'] = final_df['text'].apply(shorten_text)

In [10]:
final_df.head(30)

,title,text,label
0,N.C. governor signs bill repealing Charlotte t...,winston salem n c reuters north carolina s gov...,1
1,"Clinton, Trump clash over economy in final cam...",cleveland hershey pa reuters democrat hillary ...,1
2,Chris Wallace Gets NC Governor To Admit That ...,fox host chris wallace pinned bigoted north ca...,0
3,Pastor Shot And Killed In The Middle Of Churc...,a routine church service at the st peter s mis...,0
4,"BLACK BOSTON COP Taunted By Black Woman: ""You ...",we ve seen an escalation in violence against p...,0
5,"Ardern to be next New Zealand PM, spelling cha...",wellington reuters new zealand will get its yo...,1
6,even fox news is outraged at boehner and netan...,fox news is not exactly known as an ally of th...,0
7,Unusual Star Appears Only in Reflections,People see the star in mirrors but not in the ...,0
8,Japan health ministry to water down proposal o...,tokyo reuters japan s health ministry is likel...,1
9,Forest Wind Generates Musical Arcs Above Tree ...,Air flows create shimmering sound waves visibl...,0
10,N.J. Governor Chris Christie accosts heckler i...,new york reuters new jersey governor chris chr...,1
11,Republicans join push to lift secrecy around m...,washington reuters prominent republican senato...,1
12,New York governor calls for amending state con...,new york reuters new york governor andrew cuom...,1
13,"Russian, Iranian presidents discuss Iraqi Kurd...",london reuters russian president putin and his...,1
14,Fox News Mocked Into Oblivion After This F*ck...,in a desperate attempt to make steve bannon se...,0
15,U.S. officials working to restore public trust...,washington reuters u s attorney general lorett...,1
16,U.S. visas issued to citizens of Trump travel ...,washington reuters the united states issued ab...,1
17,trudeau confronts canada's failure of indigeno...,ottawa reuters prime minister justin trudeau o...,0
18,"leon chlon, phd",... today. You will also pay the triple lock o...,1
19,U.S. House lawmaker to release revamped Dodd-F...,washington reuters the head of the u s house o...,1
20,"Trump chooses congressman, former SEAL Zinke a...",washington reuters president elect donald trum...,1
21,STATUE OF LIBERTY AS A MUSLIM? Congressman Spa...,here we go again another student art contest t...,0
22,LIBERAL LUNATIC CHRIS MATTHEWS Scolded By Pier...,who knew former cnn anchor piers morgan would ...,0
23,Mexico enshrines army's role in drug war with ...,mexico city reuters mexico s congress on frida...,1
24,BREAKING VIDEO: Clinton Can't Explain Discrepa...,lying liar pants continues to fudge and hedge ...,0
25,"Battered U.S. coal industry hopes for Trump, p...",washington reuters republican presidential nom...,1
26,"Trump, McConnell say they remain united on sha...",washington reuters u s president donald trump ...,1
27,europe hopes for clinton win for more deals wi...,europe hopes for clinton win for more deals wi...,1
28,u.s. senate advances nomination of tillerson a...,washington reuters the u s senate advanced the...,0
29,Australian PM says he's confident Trump won't ...,sydney reuters australian prime minister malco...,1

In [26]:
# Create mask for short titles (less than 5 words)
mask = final_df['title'].str.split().str.len() < 6

# Count them
print("Total short title rows:", mask.sum())

# Show those rows
print(final_df[mask][['title']].head(20))

Total short title rows: 1309
                                                 title
18                                     leon chlon, phd
45                            post-election to-do list
52                       u.s. and world news headlines
94            Iraq's Kurdistan region delays elections
192                  Researchers Detect Silent Thunder
194            will obama recognize palestinian state?
197  hillary clinton's postapocalyptic hellscape pl...
257      What's behind Vietnam's corruption crackdown?
293         Factbox: Trump's 10-point immigration plan
304                                 re: vladimir putin
310                    MESSAGE TO HOLLYWOOD GOES VIRAL
351                            news | world bank group
511                                        darpa: home
565                                           politics
596                                 on trump's victory
621                           remarks: secretary rubio
731                                           imf news
734                        statements : press releases
880                     when charlottesville was nuked
896                        current events & world news

In [27]:
# Remove rows with short titles (less than 5 words)
full_df = final_df[~mask].reset_index(drop=True)

print("Remaining rows:", final_df.shape)

Remaining rows: (52507, 3)

In [29]:
import random
def mix_input(title, text):
    if random.random() < 0.3:
        return title
    else:
        return title + " " + text[:200]

In [2]:
import pandas as pd
df=pd.read_csv("../data/previousfinal.csv")

In [3]:
import re

def clean_title(text):
    if pd.isna(text):
        return text

    text = text.lower()
    
    # Remove abusive words (basic)
    text = re.sub(r'f\*cking|stupid|bitch|lunatic', '', text)
    
    # Fix spacing issues
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df['title'] = df['title'].apply(clean_title)

In [5]:
import re

def clean_title(text):
    if pd.isna(text):
        return text
    
    # Remove [video], [VIDEO], etc.
    text = re.sub(r'\[.*?\]', '', text)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df['title'] = df['title'].apply(clean_title)

In [7]:
import re

def clean_brackets(text):
    if pd.isna(text):
        return text
    
    # Remove only useless brackets
    text = re.sub(r'\((video|details|update|tweet|photo)\)', '', text, flags=re.IGNORECASE)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df['title'] = df['title'].apply(clean_brackets)

In [9]:
import re

def remove_small_brackets(text):
    if pd.isna(text):
        return text
    
    # Remove brackets where inside length < 6 characters
    text = re.sub(r'\([^)]{0,5}\)', '', text)
    
    # Clean extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df['title'] = df['title'].apply(remove_small_brackets)

In [11]:
import re

# Remove (tweets) specifically (case-insensitive)
df['title'] = df['title'].str.replace(r'\(tweets\)', '', regex=True, flags=re.IGNORECASE)

# Clean extra spaces
df['title'] = df['title'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [12]:
df.to_csv("../data/previousfinal22.csv",index=False)

Misleading data that generated with gpt

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/misleading_dataset.csv")

In [3]:
df.head(10)

,title,content,label_text
0,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
1,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
2,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
3,“We've had regime change.”,“We've had regime change.”,NaN
4,Milk prices “currently are no higher than they...,Milk prices “currently are no higher than they...,NaN
5,“More Americans are working today than at any ...,“More Americans are working today than at any ...,NaN
6,Video shows ICE agent removing “US citizen on ...,Video shows ICE agent removing “US citizen on ...,NaN
7,Image shows President Donald Trump asked Flori...,Image shows President Donald Trump asked Flori...,NaN
8,"""Mail-in voting means mail-in cheating.”","""Mail-in voting means mail-in cheating.”",NaN
9,The SAVE America Act “requires everyone to re-...,The SAVE America Act “requires everyone to re-...,NaN

In [4]:
df1=df.rename(columns={"content":"text"})

In [5]:
df1.head(10)

,title,text,label_text
0,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
1,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
2,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
3,“We've had regime change.”,“We've had regime change.”,NaN
4,Milk prices “currently are no higher than they...,Milk prices “currently are no higher than they...,NaN
5,“More Americans are working today than at any ...,“More Americans are working today than at any ...,NaN
6,Video shows ICE agent removing “US citizen on ...,Video shows ICE agent removing “US citizen on ...,NaN
7,Image shows President Donald Trump asked Flori...,Image shows President Donald Trump asked Flori...,NaN
8,"""Mail-in voting means mail-in cheating.”","""Mail-in voting means mail-in cheating.”",NaN
9,The SAVE America Act “requires everyone to re-...,The SAVE America Act “requires everyone to re-...,NaN

In [6]:
from ftfy import fix_text

df1["title"] = df1["title"].astype(str).apply(fix_text)
df1["text"] = df1["text"].astype(str).apply(fix_text)

In [7]:
import re

def clean_text(text):
    # remove weird characters
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    
    # fix spaces
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

df1["title"] = df1["title"].apply(clean_text)
df1["text"] = df1["text"].apply(clean_text)

In [8]:
df1["title"] = df1["title"].str.replace(r'([a-z])([A-Z])', r'\1 \2', regex=True)

In [9]:
df2 = df1[df1["title"].str.strip() != ""]

In [10]:
df2.head(10)

,title,text,label_text
0,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
1,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
2,New York leads the nation in population loss.,New York leads the nation in population loss.,NaN
3,"""We've had regime change.""","""We've had regime change.""",NaN
4,"Milk prices ""currently are no higher than they...","Milk prices ""currently are no higher than they...",NaN
5,"""More Americans are working today than at any ...","""More Americans are working today than at any ...",NaN
6,"Video shows ICE agent removing ""US citizen on ...","Video shows ICE agent removing ""US citizen on ...",NaN
7,Image shows President Donald Trump asked Flori...,Image shows President Donald Trump asked Flori...,NaN
8,"""Mail-in voting means mail-in cheating.""","""Mail-in voting means mail-in cheating.""",NaN
9,"The SAVE America Act ""requires everyone to re-...","The SAVE America Act ""requires everyone to re-...",NaN

In [22]:
df3=df2.drop("label_text",axis=1)

In [23]:
df3['label'] = 2
df3.head(10)

,title,text,label
0,New York leads the nation in population loss.,New York leads the nation in population loss.,2
1,New York leads the nation in population loss.,New York leads the nation in population loss.,2
2,New York leads the nation in population loss.,New York leads the nation in population loss.,2
3,"""We've had regime change.""","""We've had regime change.""",2
4,"Milk prices ""currently are no higher than they...","Milk prices ""currently are no higher than they...",2
5,"""More Americans are working today than at any ...","""More Americans are working today than at any ...",2
6,"Video shows ICE agent removing ""US citizen on ...","Video shows ICE agent removing ""US citizen on ...",2
7,Image shows President Donald Trump asked Flori...,Image shows President Donald Trump asked Flori...,2
8,"""Mail-in voting means mail-in cheating.""","""Mail-in voting means mail-in cheating.""",2
9,"The SAVE America Act ""requires everyone to re-...","The SAVE America Act ""requires everyone to re-...",2

In [25]:
df4 = df3.drop_duplicates(subset=['title', 'text']).reset_index(drop=True)

In [29]:
import re

def clean_text(text):
    text = text.lower()
    
    # Remove quotes
    text = re.sub(r"[\"']", "", text)
    
    # Remove non-English (basic filter)
    if not re.search(r'[a-zA-Z]', text):
        return None
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df4['title'] = df4['title'].apply(clean_text)
df4['text'] = df4['text'].apply(clean_text)

# Remove rows where either becomes None
df5 = df4.dropna(subset=['title', 'text']).reset_index(drop=True)

In [30]:
df5.to_csv("../data/misleadingfile.csv", index=False, encoding="utf-8")

In [24]:
df3.head(10)

,title,text,label
0,New York leads the nation in population loss.,New York leads the nation in population loss.,2
1,New York leads the nation in population loss.,New York leads the nation in population loss.,2
2,New York leads the nation in population loss.,New York leads the nation in population loss.,2
3,"""We've had regime change.""","""We've had regime change.""",2
4,"Milk prices ""currently are no higher than they...","Milk prices ""currently are no higher than they...",2
5,"""More Americans are working today than at any ...","""More Americans are working today than at any ...",2
6,"Video shows ICE agent removing ""US citizen on ...","Video shows ICE agent removing ""US citizen on ...",2
7,Image shows President Donald Trump asked Flori...,Image shows President Donald Trump asked Flori...,2
8,"""Mail-in voting means mail-in cheating.""","""Mail-in voting means mail-in cheating.""",2
9,"The SAVE America Act ""requires everyone to re-...","The SAVE America Act ""requires everyone to re-...",2